baseURL = 'https://hnnmehic.github.io/'
languageCode = 'en-us'
title = 'Hanan Mehic Blog'
theme = "beautifulhugo"

# [security]
#   enableInlineShortcodes = false
#
#   [security.exec]
#     allow = ['^asciidoctor$', '^dart(-sass)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$']

